### ISSUE TITLE
crashes on stop

### ISSUE THREAD

**Issue by gaming-hacker** [genedelisa/AVFoundationRecorder#1]
hello,

the app records and stop but when the window comes up to Keep or Delete and you push delete, it crashes.

fatal error: unexpectedly found nil while unwrapping an Optional value

thanks

xcode 6.2.b4
iOS 8.1 and 8.2

**Comment by bradddd** [comment]
That's because  self.recorder.deleteRecording() on line 384 of RecorderViewController.swift is nil.

It should just be the recorder parameter passed in:

```
recorder.deleteRecording() 
```

**Comment by genedelisa** [comment]
Fixed.
I was setting self.recorder to nil in stop() for a reason that no longer exists

**Comment by gaming-hacker** [comment]
thanks
