### ISSUE TITLE
How to Convert any type of audio to OPUS codec using SWIFT 4 , IOS 8 

### ISSUE THREAD

**Issue by BilalMaarbani** [genedelisa/AVFoundationRecorder#11]
please any body can help to convert any type of audio to opus codec, I just tried ( https://opus-codec.org) but this website doesn't have an example of how can I use the functionality of opus on my project, so please any body can help me ? 

my E-mail : bilal.maarbanii@gmail.com

Thank you.

**Comment by genedelisa** [comment]
My example here uses just the built in AVFoundation capabilities.

[This](https://github.com/chrisballinger/Opus-iOS) seems to be an Opus project.
