### ISSUE TITLE
how to record audio  .mp3 or .wav  ??

### ISSUE THREAD

**Issue by IOSDeveloperProgrammer** [genedelisa/AVFoundationRecorder#14]
@genedelisa  thanks for giving beautiful avfoundation recorder.  In app i need to record audio in .mp3 or .wav format. how to recored it format ??

perhaps, I was getting crashed app  when i was tried change extension .mp3 or  .wav instead of .m4a. it recorded .m4a format only. 

please help me how to recored .mp3 or .wav or  how to convert .m4a to mp3 or wav format and file size ??

Thanking you

**Comment by genedelisa** [comment]
Modify this to the format you want

let recordSettings: [String: Any] = [
            AVFormatIDKey: kAudioFormatAppleLossless,
            AVEncoderAudioQualityKey: AVAudioQuality.max.rawValue,
            AVEncoderBitRateKey: 32000,
            AVNumberOfChannelsKey: 2,
            AVSampleRateKey: 44100.0
        ]
