### ISSUE TITLE
Call recorder

### ISSUE THREAD

**Issue by ice1x** [genedelisa/AVFoundationRecorder#15]
Hello!
Could you please advise me - is it possible to add call recording to this app (i mean if i fork it with minimal clang knowledges) ? 
I guess you as a owner of audio recorder should be able to estimate resources and human-hours required for this task execution, is it even possible?

Would be very helpful, if you can find few minutes to answer.
Best regards,

**Comment by genedelisa** [comment]
Not with AVFoundation or Core Audio.

Here's an older answer that uses Core Telephony

https://stackoverflow.com/questions/1809347/how-can-i-record-a-conversation-phone-call-on-ios

**Comment by ice1x** [comment]
@genedelisa Thank you very much for quick response!
