### ISSUE TITLE
hi genedelisa

### ISSUE THREAD

**Issue by ericpols** [genedelisa/AVFoundationRecorder#7]
your exxample is very good. i added a function for play MP3. I want to record  with music and mixed. but i dont hear music after audio record. it is too low. without headphone everything is good. :(

   func PlayMusicAndRecord()

```
{  
    do {
        let url = "http://files.parsetfss.com/461a4eda-d153-4d46-bd85-28ddd355a94c/tfss-03d4eb57-51cb-424d-8c90-2d8a89429203-00255--How_To_Build_A_Loving_Family.mp3"
        let soundData = NSData(contentsOfURL: NSURL(string: url)!)
        self.player = try AVAudioPlayer(data: soundData!)
        player!.volume   = 1.0
        player!.prepareToPlay()
        player!.play() 
    }

    catch let error as NSError {
        self.player = nil
        print(error.localizedDescription)
    }
}
```

**Comment by genedelisa** [comment]
When you play it back, make certain that the session is set to playback.

**Comment by ericpols** [comment]
you dont understand me sir.  i want to make a karaoke app. record my voice and a remote mp3.
