### ISSUE TITLE
Swift 3 Update && Issue with volume levels

### ISSUE THREAD

**Issue by StephenClarkApps** [genedelisa/AVFoundationRecorder#8]
Problems experience when trying to convert this myself to the new syntax etc. 

I notice that there is an issue that when I first use the app the playback is at a nice level, but then as I continue to use it the audio goes very quiet. 

It seems that if you record two audio files in a short space of time the second recording overrides the first, this might be because the same name is being used and the app hasn't checked if there is already a file with that name.

When I try to rename a sound, unless I give it a name in the format "abcde.m4a" it vanishes from the view and I can't play or retrieve it.

It is not intuitive to a user initially that a double tap is to rename and press to delete as this is not the current iOS typical functionality, which incidentally is swipe left and swipe right to delete or rename.

**Comment by genedelisa** [comment]
Currently I've had to actually do work "for work". Just because they pay me they expect me to work. The nerve! :)

I'll update it this week sometime.
