### ISSUE TITLE
Recording after a Pause

### ISSUE THREAD

**Issue by ThiagoCM** [genedelisa/AVFoundationRecorder#9]
Hi,
I've been using your project and I've found out that if you try to save a file after pausing the record action, the application issues an error. I did not have the time to change it because my project is for a quick 3-week-course.
Thanks for sharing the project, it helped me a lot!

**Comment by ThiagoCM** [comment]
Actually I've ""fixed"" it by taking out the Pause button when you're recording something. So, you could just Stop after a Record action is issued. But that's not fixing it, just avoiding the problem.

**Comment by Mamtak1811** [comment]
Any Workaround found for this where continue and pause can be used?

**Comment by genedelisa** [comment]
Updated with a simple nil check in updateMeter
